/**
 * The production resolver must agree with the boundaries that were approved.
 *
 * The ONI and AWK polygons were drawn and validated in Python, and signed off
 * against all 972 historical pickups on 30 August 2026. Production runs
 * TypeScript. If the two implementations disagree by so much as a metre, then
 * production is resolving rides against a boundary nobody approved — and the
 * failure would be silent, because both would look perfectly reasonable.
 *
 * So the Python emitted a frozen fixture of expected answers and this suite
 * asserts against it. The fixture is data, not code: it is not regenerated by
 * the build, and a change to it is a change to an approved decision.
 */
import fixture from '../fixtures/service_zone_golden.json';
import { resolveAgainst } from '../../src/services/service_zone_resolver';
import { LoadedZone } from '../../src/services/service_zone_service';
import { boundingBox, LatLng, toGeoJson, fromGeoJson } from '../../src/services/service_zone_geometry';
import { ServiceZoneStatus, ZoneEnforcement } from '../../src/models/ServiceZone';

const ZONES: LoadedZone[] = fixture.zones.map((z: any) => {
    const polygon = z.polygon.map((p: number[]) => [p[0], p[1]] as LatLng);
    return {
        code: z.code,
        name: z.name,
        polygon,
        box: boundingBox(polygon),
        bufferMeters: z.bufferMeters,
        priority: z.priority,
        status: ServiceZoneStatus.ACTIVE,
        enforcement: ZoneEnforcement.OFF,
        radiusTiersKm: null,
    };
});

describe('service zone resolver — agreement with the approved boundaries', () => {
    it('has the approved geometry: ONI 12 vertices, AWK 9', () => {
        const oni = ZONES.find((z) => z.code === 'ONI')!;
        const awk = ZONES.find((z) => z.code === 'AWK')!;
        expect(oni.polygon).toHaveLength(12);
        expect(awk.polygon).toHaveLength(9);
        expect(oni.bufferMeters).toBe(400);
        expect(awk.bufferMeters).toBe(400);
    });

    it.each(fixture.vectors.map((v: any) => [v.label, v]))(
        'resolves %s as approved',
        (_label, v: any) => {
            const r = resolveAgainst({ lat: v.lat, lng: v.lng }, ZONES);
            expect(r.kind).toBe(v.expect.kind);
            if (r.kind === 'inside') {
                expect(r.zoneCode).toBe(v.expect.zoneCode);
                expect(r.match).toBe(v.expect.match);
            } else if (r.kind === 'outside') {
                expect(r.nearestZoneCode).toBe(v.expect.nearestZoneCode);
                // Distances are rounded to the metre in both implementations;
                // 1 m of slack absorbs the different float paths, and anything
                // larger would mean the geometry genuinely diverged.
                expect(Math.abs(r.distanceM - v.expect.distanceM)).toBeLessThanOrEqual(1);
            }
        },
    );

    // ── the properties the fixture exists to protect ────────────────────

    it('resolution is deterministic — the same point, a thousand times', () => {
        const p = { lat: 6.1667, lng: 6.7833 };
        const first = JSON.stringify(resolveAgainst(p, ZONES));
        for (let i = 0; i < 1000; i += 1) {
            expect(JSON.stringify(resolveAgainst(p, ZONES))).toBe(first);
        }
    });

    it('a point on the boundary is INSIDE, not buffer-dependent', () => {
        /*
         * Ray casting is genuinely ambiguous exactly on an edge. Without the
         * on-boundary tolerance a vertex would resolve as `buffer` at 0 m — and
         * "how many rides depend on the buffer" is the single number that tells
         * us whether the boundaries are drawn correctly or are being propped up
         * by the tolerance. It has to stay trustworthy.
         */
        for (const zone of ZONES) {
            for (const [lat, lng] of zone.polygon) {
                const r = resolveAgainst({ lat, lng }, ZONES);
                expect(r.kind).toBe('inside');
                if (r.kind === 'inside') expect(r.match).toBe('exact');
            }
        }
    });

    it('the buffer is edge tolerance, not an extension of the service area', () => {
        // Asserted through the fixture's ±399/401 m probes: whatever the buffer
        // admits is recorded as `buffer`, never as `exact`.
        const admitted = fixture.vectors.filter(
            (v: any) => v.label.includes('+399m') && v.expect.kind === 'inside');
        const refused = fixture.vectors.filter(
            (v: any) => v.label.includes('+1500m'));
        expect(admitted.length).toBeGreaterThan(0);
        for (const v of admitted) expect(v.expect.match).toBe('buffer');
        for (const v of refused) expect(v.expect.kind).toBe('outside');
    });

    it('survives the GeoJSON round trip the database performs', () => {
        // The migration writes GeoJSON and reads it back before classifying. A
        // lossy round trip would move every boundary by an invisible amount.
        for (const zone of ZONES) {
            const back = fromGeoJson(toGeoJson(zone.polygon));
            expect(back).toEqual(zone.polygon.map((p) => [p[0], p[1]]));
        }
    });

    it('rejects a point that is not a point rather than calling it outside', () => {
        for (const bad of [
            { lat: NaN, lng: 6.78 },
            { lat: 6.16, lng: Infinity },
            { lat: 0, lng: 0 },            // uninitialised coordinate, not the Gulf of Guinea
            { lat: 200, lng: 6.78 },
        ]) {
            const r = resolveAgainst(bad, ZONES);
            expect(r.kind).toBe('error');
        }
    });

    it('reports an empty zone set as an error, never as "outside"', () => {
        const r = resolveAgainst({ lat: 6.1667, lng: 6.7833 }, []);
        expect(r.kind).toBe('error');
        if (r.kind === 'error') expect(r.reason).toBe('no_zones_loaded');
    });

    it('names the nearest zone when a point is outside every one', () => {
        // Asaba: across the Niger, 2.7 km from Onitsha's edge, another state.
        const r = resolveAgainst({ lat: 6.2000, lng: 6.7333 }, ZONES);
        expect(r.kind).toBe('outside');
        if (r.kind === 'outside') {
            expect(r.nearestZoneCode).toBe('ONI');
            expect(r.distanceM).toBeGreaterThan(2000);
        }
    });
});
