name: keke_driver
description: "Keke App v2 - Driver Application"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  audioplayers: ^6.1.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  socket_io_client: ^3.0.0
  image_picker: ^1.1.2
  path: ^1.9.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/keke_ring.wav
